import manganes from "./imgProducts/Manganes1.jpeg";
import manganes2 from "./imgProducts/Manganes2.jpeg";
import hematita from "./imgProducts/Hematita.jpeg";

export const products = [
  {
    id: 1,
    name: "Manganês (mg)",
    content: 0.42,
    operations: 5,
    rating: 3,
    value: 121,
    granulometry: 23,
    region: "Grande Belo Horizonte",
    image: manganes,
  },
  {
    id: 2,
    name: "Manganês2 (mg)",
    content: 0.47,
    operations: 5,
    rating: 3.5,
    value: 150,
    granulometry: 40,
    region: "Sul de Goiás",
    image: manganes2,
  },
  {
    id: 3,
    name: "Hematita (Fe2O3)",
    content: 0.7,
    operations: 5,
    rating: 2.5,
    value: 107,
    granulometry: 15,
    region: "Quadrilátero Ferrífero",
    image: hematita,
  },
  {
    id: 4,
    name: "Nome do mineral",
    content: 0.2,
    operations: 5,
    rating: 3.5,
    value: 18000,
    granulometry: 1,
    region: "Região",
    image: "",
  },
  {
    id: 5,
    name: "Abcde",
    content: 0.2,
    operations: 5,
    rating: 3.5,
    value: 18000,
    granulometry: 1,
    region: "Região",
    image: "",
  },
];
