import manganes from "./imgProducts/Manganes1.jpeg";
import manganes2 from "./imgProducts/Manganes2.jpeg";
import hematita from "./imgProducts/Hematita.jpeg";

export const products = [
  {
    id: 1,
    name: "Manganês (mg)",
    content: 0.42,
    operations: 5,
    rating: 5,
    value: 121,
    granulometry: "23 - 30 mm",
    region: "Grande Belo Horizonte",
    image: manganes,
  },
  {
    id: 2,
    name: "Manganês (mg)",
    content: 0.47,
    operations: 5,
    rating: 3.5,
    value: 150,
    granulometry: "40 - 42 mm",
    region: "Sul de Goiás",
    image: manganes2,
  },
  {
    id: 3,
    name: "Hematita (Fe2O3)",
    content: 0.7,
    operations: 5,
    rating: 2.5,
    value: 107,
    granulometry: "15 - 20 mm",
    region: "Quadrilátero Ferrífero",
    image: hematita,
  },
  {
    id: 4,
    name: "Nome do mineral",
    content: 0.2,
    operations: 5,
    rating: "",
    value: 18000,
    granulometry: "23 - 30 mm",
    region: "Região",
    image: "",
  },
  {
    id: 5,
    name: "Nome do mineral",
    content: 0.2,
    operations: 5,
    rating: "",
    value: 18000,
    granulometry: "23 - 30 mm",
    region: "Região",
    image: "",
  },
  {
    id: 6,
    name: "Nome do mineral",
    content: 0.2,
    operations: 5,
    rating: "",
    value: 18000,
    granulometry: "23 - 30 mm",
    region: "Região",
    image: "",
  },
  {
    id: 7,
    name: "Nome do mineral",
    content: 0.2,
    operations: 5,
    rating: "",
    value: 18000,
    granulometry: "23 - 30 mm",
    region: "Região",
    image: "",
  },
  {
    id: 8,
    name: "Nome do mineral",
    content: 0.2,
    operations: 5,
    rating: "",
    value: 18000,
    granulometry: "23 - 30 mm",
    region: "Região",
    image: "",
  },
  {
    id: 9,
    name: "Nome do mineral",
    content: 0.2,
    operations: 5,
    rating: "",
    value: 18000,
    granulometry: "23 - 30 mm",
    region: "Região",
    image: "",
  },
];
